export const MARKS = {
	APP_READY: "APP_READY",
	APP_START: "APP_START",

	MAIN_WINDOW_START: "MAIN_WINDOW_START",
	MAIN_WINDOW_READY: "MAIN_WINDOW_READY",
	MAIN_WINDOW_WEBCONTENT_READY: "MAIN_WINDOW_WEBCONTENT_READY",
};